version: "2"

linters:
  enable:
    - revive
    - gosec
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - misspell

  settings:
    revive:
      rules:
        - name: exported
        - name: package-comments
        - name: var-naming
        - name: error-strings
        - name: context-as-argument
    gosec:
      excludes:
        - G104

  exclusions:
    rules:
      - path: _test\.go
        linters: [gosec, errcheck]

formatters:
  enable:
    - gofmt
    - goimports
